### ISSUE TITLE
Most kanji marked as "learned"

### ISSUE THREAD

**Issue by sleepyspider1** [digas99/wanikani-kanji-highlighter#2]
I'm on level 3.
It marks most kanji as "learned" when they are not.
Here is my read-only api token to test with: c2e9b969-7d24-4064-90da-600363adc17c
Just go to easy nhk news to test.

**Comment by digas99** [comment]
I see, I will look into it right away.
Can you tell me if you have reseted your account ever? Just to understand if it might be causing the issue.

**Comment by digas99** [comment]
Ok, I fixed it! It won't be updated just yet though, only on the next release. It will be soon, probably in a week or so.

**Comment by sleepyspider1** [comment]
Np. Thanks for the quick response!
