### ISSUE TITLE
Feature: add a "no highlighting" option as a 4th highlight style?

### ISSUE THREAD

**Issue by maximedrouhin** [digas99/wanikani-kanji-highlighter#36]
Hi!

I'd like to suggest what's in the title, for people like me who want a minimalist experience and just show the known kanji and not the unknown kanji. UX-wise that could simply be a fourth "A" letter in a rectangle, with no color whatsoever (that times 2 for the 2 rows). What do you think?

<img width="323" alt="image" src="https://github.com/user-attachments/assets/58d02108-ff25-46bf-bf4e-69b50f9c408f">

**Comment by digas99** [comment]
Hi, for sure! I'll take care of it, thank you for the feedback!
