### ISSUE TITLE
Enhancement: move icons that are not tabs out of the right sidebar

### ISSUE THREAD

**Issue by maximedrouhin** [digas99/wanikani-kanji-highlighter#37]
Hi!

I noticed that when I'm trying to explore a bit the extension and see each of the tabs (home, settings, ...), I end up clicking one of a few icons that are not actually tabs but buttons that launch an action: the Dark theme button, the Blacklist button, the Random button and the Exit button.

This is especially annoying when I click the Exit button while I just thought I was clicking on a tab, and find myself needing to find my API key in the WK settings.

Currently, there is nothing that distinguishes visually the buttons from the tabs, which probably leads others to make the same mistake. Do you think you could fix that by putting those buttons somewhere else? Maybe just putting them on the bottom of the side bar and making them look more like buttons and less like tabs could be enough. What do you think?

**Comment by digas99** [comment]
Hi, I never realized that could be an issue. Makes a lot of sense, I'll make that division!
